name: Actualizar datos de divisas

on:
  schedule:
    - cron: '0 12 1 * *'  # Cada 1 de mes a las 12:00 UTC (~7:00 a.m. Colombia)
  workflow_dispatch:        # Permite ejecuci칩n manual desde GitHub

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: 游닌 Clonar repositorio
        uses: actions/checkout@v4

      - name: 游냀 Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 游닍 Instalar dependencias
        run: pip install -r requirements.txt

      - name: 游 Ejecutar script para obtener los datos de la API fixer
        run: api_divisas.py

      - name: 游 Ejecutar script para predicci칩n
        run: divisas.py

      - name: 游닋 Subir cambios al repositorio
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add monedas.csv
          git commit -m "Actualizaci칩n autom치tica de datos de divisas"
          git push
